config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :markers

  root 'static#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/companies_marker.rb
class CompaniesMarker < ApplicationRecord

	belongs_to :marker
	belongs_to :company

end

app/models/company.rb
class Company < ApplicationRecord

	has_many :companies_markers
	has_many :markers, through: :companies_markers

	def owned_by
		markers.where(companies_markers: { owner?: true })
	end

	def hired_out_to
		markers.where(companies_markers: { owner?: false })
	end

	def self.remove_duplicates
		Company.group("lower(companies.name)").having("count(lower(companies.name))>1").count
		#.select("COUNT(*) AS count_all, lower(companies.name) AS lower_companies_name, array_agg(companies.name) AS company_ids")
	end
end

app/models/marker.rb
class Marker < ApplicationRecord

	has_many :companies_markers
	has_many :companies, through: :companies_markers

	accepts_nested_attributes_for :companies_markers

	geocoded_by :address   # can also be an IP address
	after_validation :geocode

	reverse_geocoded_by :lat, :lng
	after_validation :reverse_geocode  # auto-fetch address

	def owners
		companies.where(companies_markers: { owner?: true })
	end

	def landlords
		companies.where(companies_markers: { owner?: false })
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  after_action :set_csrf_cookie_for_ng

  private
  	def set_csrf_cookie_for_ng
      cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all.includes(:markers)
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    Marker.where(lat:nil, lng: nil).take(10).each(&:save)
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :description)
    end
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  before_action :set_marker, only: [:show, :edit, :update, :destroy]

  # GET /markers
  # GET /markers.json
  def index
    @markers = Marker.where.not(lat: nil, lng: nil).includes(:companies).order(:id)
  end

  # GET /markers/1
  # GET /markers/1.json
  def show
    Marker.where(lat:nil, lng: nil).take(5).each(&:save)
  end

  # GET /markers/new
  def new
    @marker = Marker.new
  end

  # GET /markers/1/edit
  def edit
  end

  # POST /markers
  # POST /markers.json
  def create
    @marker = Marker.new(marker_params)

    respond_to do |format|
      if @marker.save
        format.html { redirect_to @marker, notice: 'Marker was successfully created.' }
        format.json { render :show, status: :created, location: @marker }
      else
        format.html { render :new }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /markers/1
  # PATCH/PUT /markers/1.json
  def update
    respond_to do |format|
      if @marker.update(marker_params)
        format.html { redirect_to @marker, notice: 'Marker was successfully updated.' }
        format.json { render :show, status: :ok, location: @marker }
      else
        format.html { render :edit }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markers/1
  # DELETE /markers/1.json
  def destroy
    @marker.destroy
    respond_to do |format|
      format.html { redirect_to markers_url, notice: 'Marker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marker
      @marker = Marker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marker_params
      params.require(:marker).permit(:lat, :lng, :name, :description, companies_markers_attributes: [:id, :changed_responsibility_at, :owner?, :company_id])
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :name, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.text_field :name, id: :company_name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :description, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.text_area :description, id: :company_description, class: "form-control", style: "min-height:100px;" %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<div class="container-fluid">

	<h1>Editing Company</h1>

	<%= render 'form', company: @company %>

	<%= render 'markers/table', markers: @company.markers %>

	<%= link_to 'Show', @company %> |
	<%= link_to 'Back', companies_path %>
</div>

app/views/companies/index.html.erb
<div class="container-fluid">

  <p id="notice"><%= notice %></p>

  <h1>Companies</h1>

  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>#Immobilien</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @companies.each do |company| %>
        <tr>
          <td><%= company.id %></td>
          <td><%= company.name %></td>
          <td><%= company.description %></td>
          <td><%= company.markers.count %></td>
          <td><%= link_to 'Show', company %></td>
          <td><%= link_to 'Edit', edit_company_path(company) %></td>
          <!-- <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Company', new_company_path %> | <%= link_to 'Markerübersicht', markers_path %>
</div>

app/views/companies/new.html.erb
<div class="container-fluid">

	<h1>New Company</h1>

	<%= render 'form', company: @company %>

	<%= link_to 'Back', companies_path %>
</div>

app/views/companies/show.html.erb
<div class="container-fluid">
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Name:</strong>
	  <%= @company.name %>
	</p>

	<p>
	  <strong>Description:</strong>
	  <%= @company.description %>
	</p>

	<%= render 'markers/table', markers: @company.markers %>

	<%= link_to 'Edit', edit_company_path(@company) %> |
	<%= link_to 'Back', companies_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="bmgApp">
<head>
  <title>BmgMap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body ng-controller="ApplicationCtrl">

<%= yield %>

</body>
</html>

app/views/markers/_form.html.erb
<%= form_with(model: marker, local: true) do |form| %>
  <% if marker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(marker.errors.count, "error") %> prohibited this marker from being saved:</h2>

      <ul>
      <% marker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :name, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.text_field :name, id: :marker_name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :description, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.text_area :description, id: :marker_description, class: "form-control", style: "min-height:100px;" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :company_ids, "Immobilienhai", class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.collection_select :company_ids, Company.order(:name), :id, :name, {include_blank: true}, {multiple: false, class: "form-control"} %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/markers/_table.html.erb
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th colspan="2">Koordinaten</th>
      <th>aktueller Besitzer</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% markers.each do |marker| %>
      <tr>
        <td>#<%= marker.id %></td>
        <td><%= marker.name %></td>
        <td>Lat: <%= marker.lat %></td>
        <td>Lng: <%= marker.lng %></td>
        <td><%= marker.companies.last.try(:name) %></td>
        <td><%= link_to 'Show', marker %></td>
        <td><%= link_to 'Edit', edit_marker_path(marker) %></td>
        <!-- <td><%= link_to 'Destroy', marker, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

app/views/markers/edit.html.erb
<div class="container-fluid">

	<h1>Editing Marker</h1>

	<%= render 'form', marker: @marker %>

	<%= link_to 'Show', @marker %> |
	<%= link_to 'Back', markers_path %>

</div>

app/views/markers/index.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>

  <h1>Markers</h1>

  <%= render 'table', markers: @markers %>

  <br>

  <%= link_to 'Zur Karte', root_path %> | <%= link_to 'Unternehmensliste', companies_path %>

</div>

app/views/markers/new.html.erb
<h1>New Marker</h1>

<%= render 'form', marker: @marker %>

<%= link_to 'Back', markers_path %>

app/views/markers/show.html.erb
<div class="container-fluid">

	<p id="notice"><%= notice %></p>

	<div>
		<p>Name: <%= @marker.name %></p>
		<p>Beschreibung: <%= @marker.description %></p>
		<p>Immobilienhai: <%= @marker.companies.last ? (link_to @marker.companies.last.try(:name), company_path(@marker.companies.last)) : '' %></p>
		<p>Koordinaten: <%= @marker.lat %>, <%= @marker.lng %></p>
	</div>

	<%= link_to 'Edit', edit_marker_path(@marker) %> |
	<%= link_to 'Back', markers_path %>
</div>